- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install Correct Repository"
  include: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"
    
- name: "Install and Configure Zabbix Traps"
  include: "zabbix_trap.yml"
